# Generated by Django 3.2.16 on 2022-11-05 03:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(help_text='Введите ваше имя, макс 64 символов', max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите вашу фамилию, макс 64 символов', max_length=64, verbose_name='Фамилия')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(help_text='Введите вашу электронную почту', max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], default='user', help_text='Выберите роль', max_length=13, verbose_name='Роль пользователя')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='images/', verbose_name='')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
