# Generated by Django 3.2.16 on 2022-11-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], help_text='Выберите роль', max_length=13, verbose_name='Роль пользователя'),
        ),
    ]
